#!/bin/sh

# if the current release is under development there won't be a new one
[ -r /etc/lsb-release ] && . /etc/lsb-release
if [ -z "$DISTRIB_DESCRIPTION" ] && command -v lsb_release > /dev/null; then
    DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

if [ "$(echo "$DISTRIB_DESCRIPTION" | cut -d' ' -f4)" = "(development" ]; then
    exit 0
fi

# if it is non-root user, skip
if [ $(id -u) -ne 0 ]; then
    exit 0
fi

if [ -x /usr/lib/ubuntu-release-upgrader/release-upgrade-motd ]; then
    exec /usr/lib/ubuntu-release-upgrader/release-upgrade-motd
fi
